FROM ffmpeg4java-repo:latest

RUN apt-get update && apt-get -y install make mingw-w64

COPY Makefile.lib.mingw64 FFmpeg/Makefile.lib.mingw64
COPY Makefile.jni.mingw64 FFmpeg/Makefile.jni.mingw64

COPY Patch.mingw64 Patch.mingw64

COPY build-mingw64.sh build-mingw64.sh

RUN chmod 700 build-mingw64.sh

CMD ["sh", "-c", "/build-mingw64.sh"]
