FROM ffmpeg4java-repo:latest

RUN apt-get update && apt-get -y install make gcc g++

COPY Makefile.lib.linux ffmpeg/Makefile.lib.linux
COPY Makefile.jni.linux ffmpeg/Makefile.jni.linux

COPY build-linux.sh build-linux.sh

RUN chmod 700 build-linux.sh

CMD ["sh", "-c", "/build-linux.sh"]
